#!/bin/bash
export DOTFILES_DIR="$(dirname $0)"
SCRIPTS="${DOTFILES_DIR}/scripts"

command_exists() {
	type "$1" &>/dev/null
}

if command_exists dotfiles; then
	echo "dotfiles already initialized"
	return 0
fi

for script in ${SCRIPTS}/*.sh; do
	if ! source $script; then
		echo "Failed to source $script"
		exit 1
	fi
done
